# Generated by Django 3.2.21 on 2023-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='university_main',
            new_name='universityMain',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='university_sec',
            new_name='universitySec',
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
