# Generated by Django 5.0 on 2023-12-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='partner_universities',
            field=models.ManyToManyField(blank=True, to='universities.university'),
        ),
    ]
