# Generated by Django 5.0 on 2023-12-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_info',
            name='google_api_key',
            field=models.CharField(default='127.0.0.1', max_length=1000),
        ),
    ]
